rovib – Fortran Program
rovib Program
86 statements
Source File
Uses
unit_conversion_library
Calls
Contents
Variables
NGP i j rot instatus vmax NV NR PEC kmax NN Nmax mass rmin rmax step RMAT grid potential hamiltonian eigenvalues eigenvectors rovib_wavefunctions rovib_energies mol WORK A IWORK LWORK LIWORK INFO mesh x y knots moments threejsymbol
Variables
Type Attributes Name Initial
integer :: NGP
integer :: i
integer :: j
integer :: rot
integer :: instatus
integer :: vmax
integer :: NV
integer :: NR
integer :: PEC
integer, parameter :: kmax = 5000
double precision :: NN
double precision :: Nmax
double precision :: mass
double precision :: rmin
double precision :: rmax
double precision :: step
double precision :: RMAT(kmax,2)
double precision, allocatable :: grid(:)
double precision, allocatable :: potential(:)
double precision, allocatable :: hamiltonian(:,:)
double precision, allocatable :: eigenvalues(:)
double precision, allocatable :: eigenvectors(:,:)
double precision, allocatable :: rovib_wavefunctions(:,:,:)
double precision, allocatable :: rovib_energies(:,:)
character :: mol*4
double precision, allocatable :: WORK(:)
double precision, allocatable :: A(:,:)
integer, allocatable :: IWORK(:)
integer :: LWORK
integer :: LIWORK
integer :: INFO
integer :: mesh
double precision :: x
double precision :: y
double precision, allocatable :: knots(:,:)
double precision, allocatable :: moments(:)
real(kind=8) :: threejsymbol
Call graph
rovib calls splineinterpol, amu_to_au, wavenumber_to_hartree, dvr_radial, dsyevd, cubicsplines
splineinterpol calls locate
dvr_radial calls dacos
cubicsplines calls dgtsv