delta2 – Fortran Program
delta2 Subroutine
20 statements
Source File
subroutine delta2(a, b, c, power, k)
Arguments
Type Intent Optional Attributes Name
real :: a
real :: b
real :: c
integer :: power(ndim)
integer :: k
Calls
Called by
Contents
None
Call graph
delta2 calls decomp1, binom1, mul_div
binom1 calls decomp1, mul_div
threejsymbol calls delta2
ninej calls delta2
sixj calls delta2