mul_div – Fortran Program
mul_div Subroutine
39 statements
Source File
subroutine mul_div(p_s, power1, k1, power2, k2, power, k)
Arguments
Type Intent Optional Attributes Name
integer :: p_s
integer :: power1(k1)
integer :: k1
integer :: power2(k2)
integer :: k2
integer :: power(k)
integer :: k
Called by
Contents
None
Call graph
ninej calls mul_div, delta2
binom1 calls mul_div
threejsymbol calls mul_div, binom1, delta2
sixj calls mul_div, delta2
delta2 calls mul_div, binom1