ninej – Fortran Program
ninej Function
138 statements
Source File
function ninej(a, b, c, d, e, f, g, h, j)
Arguments
Type Intent Optional Attributes Name
real :: a
real :: b
real :: c
real :: d
real :: e
real :: f
real :: g
real :: h
real :: j
Return Value real(kind=8)
Calls
Contents
Common Blocks
mc pr
Common Blocks
common /mc/
Type Attributes Name Initial
integer :: iac(length)
integer :: sign
common /pr/
Type Attributes Name Initial
integer :: prime(ndim)
Call graph
ninej calls add_sub, amin1, decomp, store, find_prime, mul, mul_div, load, factor, muls, amax1, delta2
decomp calls store, load, divs
find_prime calls float
mul calls add_sub, store, load, muls
factor calls add_sub, store, mul, load, muls, binom, divs
delta2 calls mul_div, binom1, decomp1
binom1 calls mul_div, decomp1
binom calls store, load, muls, divs