sixj – Fortran Program
sixj Function
152 statements
Source File
function sixj(a, b, c, d, e, f)
Arguments
Type Intent Optional Attributes Name
real :: a
real :: b
real :: c
real :: d
real :: e
real :: f
Return Value real(kind=8)
Calls
Contents
Common Blocks
mc pr
Common Blocks
common /mc/
Type Attributes Name Initial
integer :: iac(length)
integer :: sign
common /pr/
Type Attributes Name Initial
integer :: prime(ndim)
Call graph
sixj calls add_sub, decomp, store, find_prime, mul, binom, mul_div, load, divs, muls, delta2
decomp calls store, load, divs
find_prime calls float
mul calls add_sub, store, load, muls
binom calls store, load, divs, muls
delta2 calls mul_div, binom1, decomp1
binom1 calls mul_div, decomp1