threejsymbol – Fortran Program
threejsymbol Function
160 statements
Source File
function threejsymbol(j1, j2, j3, m1, m2, m3)
Arguments
Type Intent Optional Attributes Name
real :: j1
real :: j2
real :: j3
real :: m1
real :: m2
real :: m3
Return Value real(kind=8)
Calls
Contents
Common Blocks
mc pr
Common Blocks
common /mc/
Type Attributes Name Initial
integer :: iac(length)
integer :: sign
common /pr/
Type Attributes Name Initial
integer :: prime(ndim)
Call graph
threejsymbol calls add_sub, decomp, store, binom1, find_prime, mul, binom, mul_div, load, divs, muls, delta2
decomp calls store, load, divs
binom1 calls mul_div, decomp1
find_prime calls float
mul calls add_sub, store, load, muls
binom calls store, load, divs, muls
delta2 calls binom1, mul_div, decomp1